CREATE 
PACKAGE PA_STUDENT AS
    PROCEDURE I_STUDENT(nID IN STUDENT.ID%TYPE,
                   sNAME IN STUDENT.NAME%TYPE,
                   sBRANCH IN STUDENT.BRANCH%TYPE,
                   sADDRESS IN STUDENT.ADDRESS%TYPE,
                   nRETURNCODE OUT NUMBER);

    PROCEDURE S_STUDENT(nID IN STUDENT.ID%tYPE,
                        STUD_REC OUT SYS_REFCURSOR);
    PROCEDURE D_STUDENT(nID IN STUDENT.ID%tYPE,
                        nRET_VALUE OUT NUMBER);
    PROCEDURE U_STUDENT(nID IN STUDENT.ID%TYPE,
                   sNAME IN STUDENT.NAME%TYPE,
                   sBRANCH IN STUDENT.BRANCH%TYPE,
                   sADDRESS IN STUDENT.ADDRESS%TYPE,
                   nRETURNCODE OUT NUMBER);


    NOT_VALID_ID EXCEPTION ;
    

END PA_STUDENT;
/
