CREATE PROCEDURE I_STUDENT (ID IN NUMBER,
                   NAME IN VARCHAR2,
                   BRANCH IN VARCHAR2,
                   ADDRESS IN VARCHAR2,
                   NRETURNCODE OUT NUMBER) AS
BEGIN

BEGIN

nReturnCode :=0;
INSERT INTO STUDENT(ID,NAME,BRANCH,ADDRESS) VALUES(ID,NAME,BRANCH,ADDRESS);

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        nReturnCode :=-1*sqlcode;
END;
END I_STUDENT;
/
