<?xml version='1.0' encoding='UTF-8'?>
<definitions targetNamespace="http://webservicedemo.tutorial.project.com/" name="CountriesService" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:tns="http://webservicedemo.tutorial.project.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://webservicedemo.tutorial.project.com/" schemaLocation="CountriesService_schema1.xsd"/>
    </xsd:schema>
  </types>
  <message name="getList">
    <part name="parameters" element="tns:getList"/>
  </message>
  <message name="getListResponse">
    <part name="parameters" element="tns:getListResponse"/>
  </message>
  <message name="addCntry">
    <part name="parameters" element="tns:addCntry"/>
  </message>
  <message name="addCntryResponse">
    <part name="parameters" element="tns:addCntryResponse"/>
  </message>
  <portType name="Countries">
    <operation name="getList">
      <input wsam:Action="http://webservicedemo.tutorial.project.com/Countries/getListRequest" message="tns:getList"/>
      <output wsam:Action="http://webservicedemo.tutorial.project.com/Countries/getListResponse" message="tns:getListResponse"/>
    </operation>
    <operation name="addCntry">
      <input wsam:Action="http://webservicedemo.tutorial.project.com/Countries/addCntryRequest" message="tns:addCntry"/>
      <output wsam:Action="http://webservicedemo.tutorial.project.com/Countries/addCntryResponse" message="tns:addCntryResponse"/>
    </operation>
  </portType>
  <binding name="CountriesPortBinding" type="tns:Countries">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="getList">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
    <operation name="addCntry">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="CountriesService">
    <port name="CountriesPort" binding="tns:CountriesPortBinding">
      <soap:address location="http://localhost:7000/Session1/CountriesPort"/>
    </port>
  </service>
</definitions>